<?php

/**
 * exlistview - module for creating and displaying listviews of content
 *
 * @copyright North Carolina State University 2010
 *
 */

/**
 * Implements hook_theme().
*/
function exlistview_theme() {
  return array(
    'exlistview_show' => array(
      'template' => 'exlistview_show'
     )
  );
}


// Implementing hook_menu for the AaE list views
function exlistview_menu() {
  $items = array();
  $items['listviews/draft'] = array(
    'title' => 'Draft Content',
    'description' => 'List view of draft content',
    'page callback' => 'exlistview_show',
    'access callback' => 'menu_permissions',
    'weight' => 1,
  );
  
  $items['listviews/ready for review'] = array(
    'title' => 'Ready for Review Content',
    'description' => 'List view of ready for review content',
    'page callback' => 'exlistview_show',
    'access callback' => 'menu_permissions',
    'weight' => 2,
  );
  
  $items['listviews/reviewed'] = array(
    'title' => 'Reviewed Content',
    'description' => 'List view of reviewed content',
    'page callback' => 'exlistview_show',
    'access callback' => 'menu_permissions',
    'weight' => 3,
  );
  
  $items['listviews/copy edited'] = array(
    'title' => 'Copy Edited Content',
    'description' => 'List view of copy edited content',
    'page callback' => 'exlistview_show',
    'access callback' => 'menu_permissions',
    'weight' => 4,
  );
  
  $items['listviews/published'] = array(
    'title' => 'Published Content',
    'description' => 'List view of published content',
    'page callback' => 'exlistview_show',
    'access callback' => 'menu_permissions',
    'weight' => 5,
  );
  
  return $items;
}

function menu_permissions() {
  global $user;
  
  if($user != NULL && $user->uid != NULL) { return true; }
  else { return false; }
}

function exlistview_show() {
  // get current user
  global $user;
  
  // get the workflow state passed in
  // defaults to draft
  switch (arg(1)) {
      case 'draft':
          $workflow_state = 1;
          break;
      case 'ready for review':
          $workflow_state = 2;
          break;
      case 'reviewed':
          $workflow_state = 3;
          break;
      case 'copy edited':
          $workflow_state = 4;
          break;
      case 'published':
          $workflow_state = 5;
          break;
      default:
          $workflow_state = 1;
  
  }
  
  // find user preference for tag filtering if it exists
  $tag_preference = db_query('SELECT * FROM {tag_preferences} WHERE user_id = :uid', array(':uid' => $user->uid))->fetchObject();
  
  if($tag_preference != false) {
    $tag_string = $tag_preference->tag_filter;
    $tag_array = explode(',', $tag_string);
    $tag_count = count($tag_array);
      
    $tag_query = db_select('taxonomy_index', 'ti');
    $tag_query->join('taxonomy_term_data', 'ttd', 'ttd.tid = ti.tid');
    $tag_query->addExpression('DISTINCT(ti.nid)', 'node_id');
    $tag_query->addExpression('COUNT(ti.nid)', 'node_count');
    $tag_query->condition('ttd.name', $tag_array, 'IN')
              ->groupBy('node_id')
              ->having("node_count = {$tag_count}");
                                
    $tagged_records = $tag_query->execute();
    $node_id_array = array();
    foreach ($tagged_records as $tagged_record) {
      array_push($node_id_array, $tagged_record->node_id);
    }
  }
  
  
  // if there were no tag prefs set or tag prefs set and records were tagged with all of them, continue w/ query,
  // otherwise, return no nodes
  if(($tag_preference == false) || ($tag_preference != false && count($node_id_array) > 0)) {
    
    $order_by = 'n.created';
    $order_direction = 'desc';
  
    if((isset($_GET['order'])) && (trim($_GET['order']) != '') && (isset($_GET['field'])) && (trim($_GET['field']) != '')) {
      $order_direction = $_GET['order'];
      $order_field = $_GET['field'];
      
      if($order_field == 'nid') {
        $order_by = 'n.nid';
      }
      else {
        $order_by = 'n.created';
      }
    
      if($order_direction == 'asc') {
        $order_direction = 'ASC';
        $next_sort_direction = array('order' => 'desc');
      }
      else {
        $order_direction = 'DESC';
        $next_sort_direction = array('order' => 'asc');
      }
    }
  
    else { 
      $next_sort_direction = array('order' => 'asc');
    }
  
    $listview_query = db_select('node', 'n')->extend('PagerDefault');
    $listview_query->fields('n');
    // if we have tag filtering going on here
    if(isset($node_id_array)) {
      $listview_query->condition('n.nid', $node_id_array, 'IN');
    }
    
    // if the selected listview is draft content, return content that's in draft workflow status 
    // or have no status at all, which would imply draft
    if($workflow_state == 1) {
      $listview_query->leftjoin('node_workflow', 'nw', 'nw.node_id = n.nid');
      $listview_query->condition(db_or()->condition('nw.status', $workflow_state)->condition('nw.nwid', NULL));
    }
    else {
      $listview_query->join('node_workflow', 'nw', 'nw.node_id = n.nid');
      $listview_query->condition('nw.status', $workflow_state);
    }
    
    $listview_query->condition(db_or()->condition('n.type', 'article')->condition('n.type', 'faq')->condition('n.type', 'event'))
                   ->limit(15) 
                   ->orderBy($order_by, $order_direction);   
    
    $listview_records = $listview_query->execute();
    
    if(isset($_GET['page'])) {
      $page_number = array('page' => $_GET['page']);
    }
    else {
      $page_number = array();
    }
  }
  // else we have no node records b/c the tag filter filtered them all out
  else {
    $listview_records = array();
    return theme('exlistview_show', array('listview_nodes' => $listview_records, 'tag_form' => drupal_get_form('exlistview_tag_form')));
  }
 
  return theme('exlistview_show', array('listview_nodes' => $listview_records, 'sort_direction' => $next_sort_direction, 'page_number' => $page_number, 'pager' => theme('pager'), 'tag_form' => drupal_get_form('exlistview_tag_form')));
}

// build the tag filter form
function exlistview_tag_form($form, &$form_state) {
  // get current user
  global $user;
  
  // find user preference for tag filtering if it exists
  $tag_preference = db_query('SELECT * FROM {tag_preferences} WHERE user_id = :uid', array(':uid' => $user->uid))->fetchObject();
  
  if($tag_preference != false) {
    $tag_default_value = $tag_preference->tag_filter;
  }
  else {
    $tag_default_value = '';
  }
  
  // build the form
  $form['filter_tags'] = array(
    '#type' => 'textfield', 
    '#title' => t('Filter by Tags (comma separated)'), 
    '#default_value' => $tag_default_value,
  );
  
  if(isset($_GET['order']) && isset($_GET['field'])) {  
    $form['sort_order'] = array('#type' => 'value', '#value' => $_GET['order']);
    $form['sort_field'] = array('#type' => 'value', '#value' => $_GET['field']);
  }
  
  $form['submit'] = array(
  '#type' => 'submit',
  '#value' => t('Filter'),
  );
  return $form;
}

// handle tag form submission
function exlistview_tag_form_submit($form, &$form_state) {
  // get current user
  global $user;
  $tags_to_filter_by = $form_state['values']['filter_tags'];
  
  // find user preference for tag filtering if it exists
  $tag_preference = db_query('SELECT * FROM {tag_preferences} WHERE user_id = :uid', array(':uid' => $user->uid))->fetchObject();
  
  // if a tag preference was found for this user, update it
  if($tag_preference != false) {
    $tags_to_save = prepare_tags($tags_to_filter_by);
    // if they are clearing out their tag filter, then delete their tag pref row
    if($tags_to_save == null) {
      db_delete('tag_preferences')
        ->condition('tpid', $tag_preference->tpid)
        ->execute();
    }
    else {
      db_update('tag_preferences')
      ->fields(array(
               'tag_filter' => $tags_to_save,
               'changed' => REQUEST_TIME,
               ))
      ->condition('tpid', $tag_preference->tpid)
      ->execute();
    }
  }
  // tag preference was not found, create a new one
  else {
    $tags_to_save = prepare_tags($tags_to_filter_by);
    if($tags_to_save != null) {
      // record the tag preference
      $fields = array(
                'user_id' => $user->uid, 
                'tag_filter' => $tags_to_save,
                'created' => REQUEST_TIME,
                'changed' => REQUEST_TIME,
      );
  
      db_insert('tag_preferences')->fields($fields)->execute();  
    }
  }
  
  drupal_set_message("Tag preferences updated successfully!");

}

// routine to clean and strip tags before inserting into the db
function prepare_tags($tag_string) {
  $return_string = '';
  // handle the case of an empty string (clearing the filter)
  if(trim($tag_string) == '') {
    return null;
  }
  $tag_array = explode(',', $tag_string);
  foreach ($tag_array as $tag) {
    $formatted_tag = trim($tag);
    // handle empty elements
    if($formatted_tag == '') {
      continue;
    }
      
    if($return_string == '') {
      $return_string .= $formatted_tag;
    }
    else {
      $return_string .= ','.$formatted_tag;
    }
  }
  
  return $return_string;
}
