<?php
// $Id: messaging_mail.module,v 1.2.2.4.2.8.6.7 2010/06/04 17:57:11 jareyero Exp $
/**
 * @file
 * Simple mail using Drupal API. Messaging method plug-in
 * 
 * This is also the base module for mail sending methods.
 */

/**
 * Implementation of hook_menu()
 */
function messaging_mail_menu() {
  $items['admin/config/messaging/method/mail'] = array(
    'title' => 'Mail',
    'description' => 'Common options for mail methods',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('messaging_mail_admin_settings'),
    'access arguments' => array('administer messaging'),
    'file' => 'messaging_mail.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;  
}

/**
 * Implementation of hook_messaging()
 * 
 * Currently the only operation supported is 'send methods' that will retrieve and array
 * with information fo the sending methods provided by this module.
 * 
 * @param $op
 *   Type of information to retrieve.
 * @return mixed
 *   Depending on $op   
 */
function messaging_mail_messaging($op, $type = NULL) {
  switch($op) {
    case 'send methods':
      $info['mail'] = array(
        'title' => t('Drupal mail'),
        'class' => 'Messaging_Mail_Method',
        'name' => t('Mail'),
        'description' => t('Get messages as plain text e-mail.'),
      );
      return $info;

    case 'address types':
      // Get some built in address types
      $types['mail'] = array(
        'name' => t('E-mail address'), // Name for display
        'class' => 'Messaging_Mail_Address',
      );
      return $types;
  }
}

/**
 * Implementation of hook_user().
 *
 * Adds fieldset and default sending method setting.
 */
function messaging_mail_user($type, $edit, &$user, $category = NULL) {
  switch ($type) {
    case 'update':
      // Claim user mail address if in destinations table
      messaging_mail_update_user($user);
  }
}

/**
 * Get list of mail methods
 */
function messaging_mail_methods() {
  $mail_methods = array();
  foreach (messaging_method_info() as $method => $info) {
    if (!empty($info['group']) && $info['group'] == 'mail') {
      $mail_methods[] = $method;
    }
  }
  return $mail_methods;
}

/**
 * Update destinations when a user account is updated, created
 * 
 * The destinations for that mail account will be assigned to the user
 */
function messaging_mail_update_user($account) {
  if ($account->status) {
    // Update mail for destinations of this user
    db_query("UPDATE {messaging_destination} SET address = '%s' WHERE uid = %d AND type = 'mail'", $account->mail, $account->uid);
    // Update uid for destinations with this mail
    db_query("UPDATE {messaging_destination} SET uid = %d WHERE uid = 0 AND type = 'mail' AND address = '%s'", $account->uid, $account->mail);
  }
}


/**
 * Send mail message to user account
 * 
 * This is a callback function that will be invoked from messaging delivery methods
 * 
 * @see messaging_message_send()
 * @see drupal_mail()
 * 
 * @param $destination
 *   Single email address
 * @param $message
 *   Message array
 * @param $params
 *   Optional parameters for this method type
 */
function messaging_mail_send_msg($address, $message, $params = array()) {
  // Build the message in drupal mail format
  $mail = $message->send_method()->mail_build($address, $message, $params);
  return drupal_mail_send($mail);
}

/**
 * Implementation of hook_disable()
 */
function messaging_mail_disable() {
  Messaging_Method::method_disable('mail');
}