<?php
// $Id$

/**
 * @file
 * Defines a eXtension JS editors advanced settings.
 */
 
function exeditor_wysiwyg_editor_settings_alter(&$settings, &$context) {
    if ($context['profile']->editor == 'ckeditor') {
      $settings['pasteFromWordRemoveFontStyles'] = 'true';
      $settings['pasteFromWordRemoveStyles'] = 'true';
      $settings['forcePasteAsPlainText'] = 'false';
      $settings['pasteFromWordPromptCleanup'] = 'false';
      $settings['protectedSource'] = '/\<code.*?\<\/code\>/g';
	  //$settings['removePlugins'] = 'contextmenu';
	  $settings['apply_source_formatting'] = 1;
      //$settings['uiColor'] = '#9AB8F3';
   }
}
  
  
  
  
/* 
* Implementation of hook_views_api() 
*/ 
function exeditor_views_api() { 
	return array('api' => 2.0); 
} 


/* 
* Implementation of hook_views_default_views() 
*/ 
function exeditor_views_default_views(){ 
	$view = views_new_view(); 
	$view->name = 'cop_nodes';
	$view->description = 'Show all nodes of a group.';
	$view->tag = 'group';
	$view->base_table = 'node';
	$view->human_name = '';
	$view->core = 0;
	$view->api_version = '3.0-alpha1';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Defaults */
	$handler = $view->new_display('default', 'Defaults', 'default');
	$handler->display->display_options['access']['type'] = 'none';
	$handler->display->display_options['cache']['type'] = 'none';
	$handler->display->display_options['query']['type'] = 'views_query';
	$handler->display->display_options['exposed_form']['type'] = 'basic';
	$handler->display->display_options['pager']['type'] = 'full';
	$handler->display->display_options['style_plugin'] = 'default';
	$handler->display->display_options['row_plugin'] = 'fields';
	/* No results behavior: Global: Text area */
	$handler->display->display_options['empty']['area']['id'] = 'area';
	$handler->display->display_options['empty']['area']['table'] = 'views';
	$handler->display->display_options['empty']['area']['field'] = 'area';
	$handler->display->display_options['empty']['area']['empty'] = FALSE;
	$handler->display->display_options['empty']['area']['content'] = 'There is no content in this group.';
	/* Relationship: Content revision: User */
	$handler->display->display_options['relationships']['uid']['id'] = 'uid';
	$handler->display->display_options['relationships']['uid']['table'] = 'node_revision';
	$handler->display->display_options['relationships']['uid']['field'] = 'uid';
	$handler->display->display_options['relationships']['uid']['required'] = 1;
	/* Field: Content: Has new content */
	$handler->display->display_options['fields']['timestamp']['id'] = 'timestamp';
	$handler->display->display_options['fields']['timestamp']['table'] = 'history';
	$handler->display->display_options['fields']['timestamp']['field'] = 'timestamp';
	$handler->display->display_options['fields']['timestamp']['label'] = '';
	$handler->display->display_options['fields']['timestamp']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['timestamp']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['timestamp']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['timestamp']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['timestamp']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['timestamp']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['timestamp']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['timestamp']['alter']['html'] = 0;
	$handler->display->display_options['fields']['timestamp']['element_label_colon'] = 1;
	$handler->display->display_options['fields']['timestamp']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['timestamp']['hide_empty'] = 0;
	$handler->display->display_options['fields']['timestamp']['empty_zero'] = 0;
	$handler->display->display_options['fields']['timestamp']['link_to_node'] = 0;
	$handler->display->display_options['fields']['timestamp']['comments'] = 0;
	/* Field: Content: Title */
	$handler->display->display_options['fields']['title']['id'] = 'title';
	$handler->display->display_options['fields']['title']['table'] = 'node';
	$handler->display->display_options['fields']['title']['field'] = 'title';
	$handler->display->display_options['fields']['title']['label'] = '';
	$handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['title']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['title']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['title']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['title']['alter']['html'] = 0;
	$handler->display->display_options['fields']['title']['element_label_colon'] = 1;
	$handler->display->display_options['fields']['title']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['title']['hide_empty'] = 0;
	$handler->display->display_options['fields']['title']['empty_zero'] = 0;
	$handler->display->display_options['fields']['title']['link_to_node'] = 1;
	/* Field: Content: Image */
	$handler->display->display_options['fields']['entity_id']['id'] = 'entity_id';
	$handler->display->display_options['fields']['entity_id']['table'] = 'field_data_field_image';
	$handler->display->display_options['fields']['entity_id']['field'] = 'field_image';
	$handler->display->display_options['fields']['entity_id']['label'] = '';
	$handler->display->display_options['fields']['entity_id']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['entity_id']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['entity_id']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['entity_id']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['entity_id']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['entity_id']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['entity_id']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['entity_id']['alter']['html'] = 0;
	$handler->display->display_options['fields']['entity_id']['element_label_colon'] = 1;
	$handler->display->display_options['fields']['entity_id']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['entity_id']['hide_empty'] = 0;
	$handler->display->display_options['fields']['entity_id']['empty_zero'] = 0;
	$handler->display->display_options['fields']['entity_id']['click_sort_column'] = 'fid';
	$handler->display->display_options['fields']['entity_id']['settings'] = array(
	  'image_style' => 'small_square',
	  'image_link' => 'content',
	);
	/* Field: Content: Body */
	$handler->display->display_options['fields']['entity_id_1']['id'] = 'entity_id_1';
	$handler->display->display_options['fields']['entity_id_1']['table'] = 'field_data_body';
	$handler->display->display_options['fields']['entity_id_1']['field'] = 'body';
	$handler->display->display_options['fields']['entity_id_1']['label'] = '';
	$handler->display->display_options['fields']['entity_id_1']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['entity_id_1']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['entity_id_1']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['entity_id_1']['alter']['trim'] = 1;
	$handler->display->display_options['fields']['entity_id_1']['alter']['max_length'] = '200';
	$handler->display->display_options['fields']['entity_id_1']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['entity_id_1']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['entity_id_1']['alter']['strip_tags'] = 1;
	$handler->display->display_options['fields']['entity_id_1']['alter']['preserve_tags'] = '<strong><em>';
	$handler->display->display_options['fields']['entity_id_1']['alter']['html'] = 0;
	$handler->display->display_options['fields']['entity_id_1']['element_label_colon'] = 1;
	$handler->display->display_options['fields']['entity_id_1']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['entity_id_1']['hide_empty'] = 0;
	$handler->display->display_options['fields']['entity_id_1']['empty_zero'] = 0;
	/* Field: Content: Updated date */
	$handler->display->display_options['fields']['changed']['id'] = 'changed';
	$handler->display->display_options['fields']['changed']['table'] = 'node';
	$handler->display->display_options['fields']['changed']['field'] = 'changed';
	$handler->display->display_options['fields']['changed']['label'] = '';
	$handler->display->display_options['fields']['changed']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['external'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['replace_spaces'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['nl2br'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['changed']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['changed']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['changed']['alter']['html'] = 0;
	$handler->display->display_options['fields']['changed']['element_label_colon'] = FALSE;
	$handler->display->display_options['fields']['changed']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['changed']['hide_empty'] = 0;
	$handler->display->display_options['fields']['changed']['empty_zero'] = 0;
	$handler->display->display_options['fields']['changed']['date_format'] = 'time ago';
	/* Field: User: First name */
	$handler->display->display_options['fields']['field_first_name']['id'] = 'field_first_name';
	$handler->display->display_options['fields']['field_first_name']['table'] = 'field_data_field_first_name';
	$handler->display->display_options['fields']['field_first_name']['field'] = 'field_first_name';
	$handler->display->display_options['fields']['field_first_name']['relationship'] = 'uid';
	$handler->display->display_options['fields']['field_first_name']['label'] = '';
	$handler->display->display_options['fields']['field_first_name']['alter']['alter_text'] = 1;
	$handler->display->display_options['fields']['field_first_name']['alter']['text'] = 'by [field_first_name]';
	$handler->display->display_options['fields']['field_first_name']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['external'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['replace_spaces'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['nl2br'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['field_first_name']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['field_first_name']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['field_first_name']['alter']['html'] = 0;
	$handler->display->display_options['fields']['field_first_name']['element_label_colon'] = FALSE;
	$handler->display->display_options['fields']['field_first_name']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['field_first_name']['hide_empty'] = 0;
	$handler->display->display_options['fields']['field_first_name']['empty_zero'] = 0;
	$handler->display->display_options['fields']['field_first_name']['field_api_classes'] = 0;
	/* Field: User: Last name */
	$handler->display->display_options['fields']['field_last_name']['id'] = 'field_last_name';
	$handler->display->display_options['fields']['field_last_name']['table'] = 'field_data_field_last_name';
	$handler->display->display_options['fields']['field_last_name']['field'] = 'field_last_name';
	$handler->display->display_options['fields']['field_last_name']['relationship'] = 'uid';
	$handler->display->display_options['fields']['field_last_name']['label'] = '';
	$handler->display->display_options['fields']['field_last_name']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['external'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['replace_spaces'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['nl2br'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['field_last_name']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['field_last_name']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['field_last_name']['alter']['html'] = 0;
	$handler->display->display_options['fields']['field_last_name']['element_label_colon'] = FALSE;
	$handler->display->display_options['fields']['field_last_name']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['field_last_name']['hide_empty'] = 0;
	$handler->display->display_options['fields']['field_last_name']['empty_zero'] = 0;
	$handler->display->display_options['fields']['field_last_name']['field_api_classes'] = 0;
	/* Sort criterion: Content: Post date */
	$handler->display->display_options['sorts']['created']['id'] = 'created';
	$handler->display->display_options['sorts']['created']['table'] = 'node';
	$handler->display->display_options['sorts']['created']['field'] = 'created';
	$handler->display->display_options['sorts']['created']['order'] = 'DESC';
	/* Contextual filter: Fields: Groups audience (group_audience:gid) */
	$handler->display->display_options['arguments']['group_audience_gid']['id'] = 'group_audience_gid';
	$handler->display->display_options['arguments']['group_audience_gid']['table'] = 'field_data_group_audience';
	$handler->display->display_options['arguments']['group_audience_gid']['field'] = 'group_audience_gid';
	$handler->display->display_options['arguments']['group_audience_gid']['default_action'] = 'default';
	$handler->display->display_options['arguments']['group_audience_gid']['default_argument_type'] = 'fixed';
	$handler->display->display_options['arguments']['group_audience_gid']['summary']['format'] = 'default_summary';
	$handler->display->display_options['arguments']['group_audience_gid']['specify_validation'] = 1;
	$handler->display->display_options['arguments']['group_audience_gid']['validate']['fail'] = 'empty';
	$handler->display->display_options['arguments']['group_audience_gid']['break_phrase'] = 0;
	$handler->display->display_options['arguments']['group_audience_gid']['not'] = 0;
	
	/* Display: Content pane */
	$handler = $view->new_display('panel_pane', 'Content pane', 'panel_pane_1');
	$handler->display->display_options['pane_title'] = 'OG nodes';
	$handler->display->display_options['allow']['use_pager'] = 0;
	$handler->display->display_options['allow']['items_per_page'] = 0;
	$handler->display->display_options['allow']['offset'] = 0;
	$handler->display->display_options['allow']['link_to_view'] = 0;
	$handler->display->display_options['allow']['more_link'] = 0;
	$handler->display->display_options['allow']['path_override'] = 0;
	$handler->display->display_options['allow']['title_override'] = 'title_override';
	$handler->display->display_options['allow']['exposed_form'] = 0;
	$handler->display->display_options['allow']['fields_override'] = 0;
	$handler->display->display_options['argument_input'] = array(
	  'group_audience_gid' => array(
		'type' => 'context',
		'context' => 'entity:group.gid',
		'context_optional' => 0,
		'panel' => '0',
		'fixed' => '',
		'label' => 'Fields: group_audience (group_audience) - gid',
	  ),
	);
	
	/* Display: Group blog */
	$handler = $view->new_display('page', 'Group blog', 'page_1');
	$handler->display->display_options['defaults']['filters'] = FALSE;
	/* Filter criterion: Content: Type */
	$handler->display->display_options['filters']['type']['id'] = 'type';
	$handler->display->display_options['filters']['type']['table'] = 'node';
	$handler->display->display_options['filters']['type']['field'] = 'type';
	$handler->display->display_options['filters']['type']['value'] = array(
	  'blog' => 'blog',
	);
	$handler->display->display_options['path'] = 'group_blog';
	
	/* Display: Group forum */
	$handler = $view->new_display('page', 'Group forum', 'page_2');
	$handler->display->display_options['defaults']['filters'] = FALSE;
	/* Filter criterion: Content: Type */
	$handler->display->display_options['filters']['type']['id'] = 'type';
	$handler->display->display_options['filters']['type']['table'] = 'node';
	$handler->display->display_options['filters']['type']['field'] = 'type';
	$handler->display->display_options['filters']['type']['value'] = array(
	  'forum' => 'forum',
	);
	$handler->display->display_options['path'] = 'group_forum';
	
	/* Display: Group articles */
	$handler = $view->new_display('page', 'Group articles', 'page_3');
	$handler->display->display_options['defaults']['filters'] = FALSE;
	/* Filter criterion: Content: Type */
	$handler->display->display_options['filters']['type']['id'] = 'type';
	$handler->display->display_options['filters']['type']['table'] = 'node';
	$handler->display->display_options['filters']['type']['field'] = 'type';
	$handler->display->display_options['filters']['type']['value'] = array(
	  'article' => 'article',
	);
	$handler->display->display_options['path'] = 'group_articles';
	
	/* Display: Group faq */
	$handler = $view->new_display('page', 'Group faq', 'page_4');
	$handler->display->display_options['defaults']['filters'] = FALSE;
	/* Filter criterion: Content: Type */
	$handler->display->display_options['filters']['type']['id'] = 'type';
	$handler->display->display_options['filters']['type']['table'] = 'node';
	$handler->display->display_options['filters']['type']['field'] = 'type';
	$handler->display->display_options['filters']['type']['value'] = array(
	  'faq' => 'faq',
	);
	$handler->display->display_options['path'] = 'group_faq';
	
	/* Display: Group events */
	$handler = $view->new_display('page', 'Group events', 'page_5');
	$handler->display->display_options['defaults']['filters'] = FALSE;
	/* Filter criterion: Content: Type */
	$handler->display->display_options['filters']['type']['id'] = 'type';
	$handler->display->display_options['filters']['type']['table'] = 'node';
	$handler->display->display_options['filters']['type']['field'] = 'type';
	$handler->display->display_options['filters']['type']['value'] = array(
	  'event' => 'event',
	);
	$handler->display->display_options['path'] = 'group_events';
	
	/* Display: Quick links */
	$handler = $view->new_display('page', 'Quick links', 'page_6');
	$handler->display->display_options['defaults']['pager'] = FALSE;
	$handler->display->display_options['pager']['type'] = 'some';
	$handler->display->display_options['pager']['options']['items_per_page'] = '7';
	$handler->display->display_options['pager']['options']['offset'] = '0';
	$handler->display->display_options['defaults']['style_plugin'] = FALSE;
	$handler->display->display_options['style_plugin'] = 'list';
	$handler->display->display_options['defaults']['style_options'] = FALSE;
	$handler->display->display_options['defaults']['row_plugin'] = FALSE;
	$handler->display->display_options['row_plugin'] = 'fields';
	$handler->display->display_options['defaults']['row_options'] = FALSE;
	$handler->display->display_options['defaults']['fields'] = FALSE;
	/* Field: Content: Title */
	$handler->display->display_options['fields']['title']['id'] = 'title';
	$handler->display->display_options['fields']['title']['table'] = 'node';
	$handler->display->display_options['fields']['title']['field'] = 'title';
	$handler->display->display_options['fields']['title']['label'] = '';
	$handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
	$handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
	$handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
	$handler->display->display_options['fields']['title']['alter']['trim'] = 0;
	$handler->display->display_options['fields']['title']['alter']['word_boundary'] = 1;
	$handler->display->display_options['fields']['title']['alter']['ellipsis'] = 1;
	$handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
	$handler->display->display_options['fields']['title']['alter']['html'] = 0;
	$handler->display->display_options['fields']['title']['element_label_colon'] = 1;
	$handler->display->display_options['fields']['title']['element_default_classes'] = 1;
	$handler->display->display_options['fields']['title']['hide_empty'] = 0;
	$handler->display->display_options['fields']['title']['empty_zero'] = 0;
	$handler->display->display_options['fields']['title']['link_to_node'] = 1;
	$handler->display->display_options['path'] = 'quicklinks';
	$translatables['cop_nodes'] = array(
	  t('Defaults'),
	  t('more'),
	  t('Apply'),
	  t('Reset'),
	  t('Sort by'),
	  t('Asc'),
	  t('Desc'),
	  t('Items per page'),
	  t('- All -'),
	  t('Offset'),
	  t('There is no content in this group.'),
	  t('revision user'),
	  t('by [field_first_name]'),
	  t('All'),
	  t('Content pane'),
	  t('OG nodes'),
	  t('View panes'),
	  t('Group blog'),
	  t('Group forum'),
	  t('Group articles'),
	  t('Group faq'),
	  t('Group events'),
	  t('Quick links'),
	); 
	$views[$view->name] = $view; 
	return $views; 
}