<?php
// $Id$

/**
 * @file
 * Defines a eXtension JS editors advanced settings.
 */
 
function exeditor_wysiwyg_editor_settings_alter(&$settings, &$context) {
    if ($context['profile']->editor == 'ckeditor') {
      $settings['pasteFromWordRemoveFontStyles'] = 'true';
      $settings['pasteFromWordRemoveStyles'] = 'true';
      $settings['forcePasteAsPlainText'] = 'false';
      $settings['pasteFromWordPromptCleanup'] = 'false';
      $settings['protectedSource'] = '/\<code.*?\<\/code\>/g';
	  $settings['removePlugins'] = 'contextmenu';
	  $settings['apply_source_formatting'] = 1;
      //$settings['uiColor'] = '#9AB8F3';
   }
}
  