<?php
// $Id$

/**
 * @file
 * Defines a eXtension JS editors advanced settings.
 */
 
function exeditor_wysiwyg_editor_settings_alter(&$settings, &$context) {
    if ($context['profile']->editor == 'ckeditor') {
      $settings['pasteFromWordRemoveFontStyles'] = 'true';
      $settings['pasteFromWordRemoveStyles'] = 'false';
      $settings['forcePasteAsPlainText'] = 'false';
	  $settings['disableNativeSpellChecker'] = FALSE;	  
      $settings['pasteFromWordPromptCleanup'] = 'false';
      $settings['protectedSource'] = '/\<code.*?\<\/code\>/g';
	  //$settings['removePlugins'] = 'contextmenu';
	  $settings['apply_source_formatting'] = 1;
      //$settings['uiColor'] = '#9AB8F3';
   }
}
  
  
  
  
/* 
* Implementation of hook_views_api() 
*/ 
function exeditor_views_api() { 
	return array('api' => 2.0); 
} 