# Define deployment targets.
# Required keys are deploy_dir and host.
# Optional keys are tag and ssh_port
demo:
    deploy_dir: "/services/apache/vhosts/create.demo.extension.org/docroot/"
    host: "create.demo.extension.org"
    branch: develop
    ssh_port: 24 
prod:
    deploy_dir: "/services/apache/vhosts/create.extension.org/docroot/"
    host: "create.extension.org"
    ssh_port: 24
    branch: master
