	<div class="region region-footer-firstrow">
		<nav id="block-menu-menu-publish-to-www" class="block block-menu">
			<h2>Publish to www.extension.org</h2>
			<div class="description">Create content to be displayed as trusted and
credable resource to the public.
			</div>
		  	<div class="links">
				<ul class="menu">
					<li class="first leaf"><a href="" title="">Content categories</a></li>
					<li class="leaf"><a href="/node/add/faq" title="">Create FAQ</a></li>
					<li class="leaf"><a href="/node/add/article" title="">Create article</a></li>
				</ul>
				<ul>
					<li class="leaf"><a href="/group_articles" title="">Latest articles</a></li>
					<li class="leaf"><a href="/my_contributions" title="">My articles</a></li>
					<li class="last leaf"><a href="/my_contributions" title="">My faq-s</a></li>
				</ul>
		  </div>
		</nav>
		<nav id="block-menu-menu-manage-your-community" class="block block-menu">
		
			<h2>Manage your community</h2>
			<div class="description">Discuss, share, organize and present your thought on
		the topics of the resource area you are member to.
			</div>
		  	<div class="links">
				<ul class="menu">
					<li class="first leaf"><a href="/node/add/blog" title="">Create blog post</a></li>
					<li class="leaf"><a href="/node/add/event" title="">Create Event</a></li>
					<li class="leaf"><a href="/blog" title="">My blogs</a></li>
				</ul>
				<ul>
					<li class="leaf"><a href="/group-list" title="">My communities</a></li>
					<li class="leaf"><a href="/group-list" title="">All communities</a></li>
					<li class="last leaf"><a href="/forum" title="">Discussions</a></li>
				</ul> 
		  </div>
		</nav>
		<nav id="block-menu-menu-about-extension" class="block block-menu">
			  <h2>About eXtension</h2>
			<div class="description">Documents, notes, guidelines and resources for 
managing eXtension organization as a whole.</div>
		<div class="links">
			<ul class="menu">
				<li class="first leaf"><a href="/node/add/public-article" title="">Create document</a></li>
				<li class="leaf"><a href="/public_articles_archive" title="">Search</a></li>
				<li class="leaf"><a href="/admin/structure/taxonomy/administrative_docs" title="">Categories</a></li>
			</ul>
			<ul>
				<li class="leaf"><a href="/administrative_term/137" title="">Organization</a></li>
				<li class="leaf"><a href="/taxonomy/term/270" title="">Engineering</a></li>
				<li class="last leaf"><a href="/taxonomy/term/138" title="">Content development</a></li>
			</ul>
		</div>
		</nav>
  </div>