<?php
/**
 * eximport - content seed from feed.
 *
 * @package eximport 
 * @version 0.1
 * @author James E. Robinson, III <james.robinson@extension.org>
 * @copyright North Carolina State University 2010
 */

// Bootstrap Drupal - if including in standalone script
// require 'includes/bootstrap.inc';
// drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

require_once 'simplehtmldom/simple_html_dom.php';
require_once 'http_build_url.php';

/**
 *
 * Import Plan
 *
 * 1. export all revisions of all articles from MW
 *    a. create XML files with about 250 articles in each
 *    b. Format as valid Atom 1.0 feed
 *    c. will have approx 1200 files after export
 *
 * 2. import revisions
 *    a. use DrupalBot as the user for publishing events
 *    b. mark all published revisions as such
 *    c. when import complete, mark all unpublished articles as draft
 *    d. import 'news' articles as content-type news, all others as articles
 *
 * 3. import images? Nope
 *
 * 4. rewrite URLs
 *    a. rewrite img src's
 *    b. rewrite wiki href's
 *
 * 5. article metadata
 *    a. ???
 */

// TODO handle publishing flag
// TODO metadata?

// confirm access to node methods
module_load_include('inc', 'node', 'node.pages', 'path', 'filter'); 

/**
 * hook_help entry-point function.
 * Let folks know what this is if they are clueless.
 *
 * @param string $path request.uri path.
 * @param array $arg pieces of uri split by '/'.
 * @return string HTML for module help.
 * @see hook_help
 */
function eximport_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#eximport":
      $output = '<p>'
              . t("To assist in the import of MediaWiki content.")
              . '</p>';
    break;
  }
  return $output;
}

/**
 * hook_permission entry-point function.
 * Add an eximport specific permission, for giggles.
 *
 * @return n/a.
 * @see hook_permission
 */
function eximport_permission() {
  return array(
    'administer import' =>  array(
      'title' => t('Administer eX Import'),
      'description' => t('Use caution.'),
    ),
  );
}

/**
 * hook_menu entry-point function.
 * Add an eximport specific routes.
 *
 * @return array $items Array of routes for this module.
 * @see hook_menu
 */
function eximport_menu() {
  $items = array();
  
  $items['admin/config/extension/import'] = array(
    'title' => 'Import Content',
    'description' => 'Tools for importing wiki data.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eximport_admin_form'),
    'access arguments' => array('administer import')
    );
    
  return $items;
}

/**
 * Define the admin form.
 *
 * @param array $form form array.
 * @param array &$form_state Reference to array with the current form state.
 * @return array Form array.
 * @see forms_api_reference
 */
function eximport_admin_form($form, &$form_state) {

  $form['filename'] = array(
    '#type' => 'textfield',
    '#title' => t('File to import'),
    '#default_value' => 'import.xml',
    '#size' => 40,
    '#maxlength' => 80,
    '#description' => t("Filename of default import file."),
    '#required' => FALSE,
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Import'));
  
  $form['rewrite'] = array('#type' => 'submit', '#value' => t('Update URLs'));
  
  return $form;
}

/**
 * Validate admin form input.
 *
 * @param array $form form array.
 * @param array &$form_state Reference to array with the current form state.
 * @return n/a
 * @see _form_validate
 */
function eximport_admin_form_validate($form, &$form_state) {
  
  switch ($form_state['values']['op']) {
    case 'Import':
      $filename = $form_state['values']['filename'];
      if ( ! preg_match('/\.(xml|atom)$/i', $filename)) {
        form_set_error('', t('A valid filename is required.'));
      } elseif ( ! eximport_verify_filename($filename) ) {
        form_set_error('', t('File must exist in import directory.'));
      }
      break;
    case 'Update URLs':
      break;
    default:
      form_set_error('', t('Invalid button pushed.'));
  }

  return;
}

/**
 * Given filename, return location of file.
 *
 * @param string $filename Input filename.
 * @return string Full path to file.
 */
function eximport_get_fullpath($filename) {
  $path_parts = array(DRUPAL_ROOT, 'import', $filename);
  return implode(DIRECTORY_SEPARATOR, $path_parts);
}

/**
 * Given filename, verify exists in file system.
 *
 * @param string $filename Input filename.
 * @return boolean True if file exists, FALSE otherwise.
 * @see _form_validate
 */
function eximport_verify_filename($filename) {
  $target = eximport_get_fullpath($filename);
  return file_exists($target);
}

/**
 * Process form after submission.
 *
 * @param array $form form array.
 * @param array &$form_state Reference to array with the current form state.
 * @return n/a
 * @see form_execute_handlers
 */
function eximport_admin_form_submit($form, &$form_state) {
  
  $cmd = $form_state['values']['op'];
  
  switch ($cmd) {
      case 'Import':
      $filename = $form_state['values']['filename'];
      list($total, $added, $errors) = eximport_import_from_file($filename);
      break;
    case 'Update URLs':
      list($total, $added, $errors) = eximport_rewrite_imported_urls();
      break;
    default:
      form_set_error('', t('Invalid button pushed.'));
  }
  
  if ($errors) {
    drupal_set_message(t($cmd . ' failed: ' 
                         . $errors . ' errors out of ' 
                         . $total . ' revisions.'), 'error');
  } else {
    drupal_set_message(t($cmd . ' successful. ' 
                         . $added . ' out of ' 
                         . $total . ' revisions.'));
  }

  return;
}

/**
 * Create a Drupal node and revision from input.
 *
 * @param object $entry Object with data for new node.
 * @return boolean TRUE if successful, FALSE otherwise
 * @see node_save
 */
function eximport_node_create($entry) {
  $rc = FALSE;
  $nid = 0;
  $new = FALSE;
  
  // First, try to see if we've imported a node with the same link
  $path = path_load(array('alias' => $entry->old_link));
  if ($path) {
    $nid = $path['source'];
  }
  unset($path);
  
  // Construct the new node object.
  
  if ($nid) {
    // reset entity_load cache - be sure we have the latest version
    $node = node_load($nid, NULL, TRUE);
    $node->revision = '1';
  } else {
    $new = TRUE;
    $node = new stdClass();
    $node->type = $entry->type;
    node_object_prepare($node);
    $node->language = LANGUAGE_NONE;
    $node->created = $entry->created;
  }
  
  $node->uid = $entry->uid;
  $node->title = $entry->title;
  
  $node->changed = $entry->created;
  
  $node->body = $entry->body;
  
  $node->field_tags = $entry->field_tags;
  node_save($node);
  
  $nid = $node->nid;
  
  if ($nid and $new) {
    eximport_save_old_link($nid, $entry->old_link);
    $rc = TRUE;
  } elseif ($nid) {
    $rc = TRUE;
  }
  
  unset($node);
  unset($entry);
  
  return $rc;
}

/**
 * Create a Drupal node and revision from input.
 *
 * @param integer $nid Node ID.
 * @param string $old_link URL for old article location.
 * @see path_inc
 */
function eximport_save_old_link($nid, $old_link) {
  $path = array('alias' => $old_link, 'source' => "$nid");
  
  $exists = path_load("$nid");
  if ($exists) {
    $path['pid'] = $exists['pid'];
  }
  
  path_save($path);
  return;
}

/**
 * Create a new content entry object from XML input.
 *
 * @param object $atom_entry SimpleXML Atom entry object.
 * @return object Generic content entry object
 */
function eximport_entry_create($atom_entry) {
  $entry = new stdClass();
  
  // default to article content-type
  $entry->type = 'article';
    
  // create our tag array
  $categories = array();
  $entry->published = FALSE;
  
  foreach ($atom_entry->category as $cat) {
    if ($cat['term'] == 'news') {
      // if it is news, change content-type
      $entry->type = 'news';
    }
    if ($cat['term'] == 'published') {
       $entry->published = TRUE;
       continue;
    }
    $cat_entry = array('vid' => '1',
                       'tid' => 'autocreate',
                       'name' => (string)$cat['term']);
    $categories[] = $cat_entry;
  }
  
  $entry->field_tags = array(LANGUAGE_NONE => $categories);
  
  // author
  $entry->uid = eximport_find_author((string)$atom_entry->author->name[0]);
  
  // duh
  $entry->title = (string)$atom_entry->title;
  
  // create our body array
  $teaser = eximport_get_teaser($atom_entry->content);
  $body = (string)$atom_entry->content;
  $entry->body = array(LANGUAGE_NONE =>
                  array(0 =>
                    array('summary' => $teaser,
                          'value' => $body,
                          'format' => filter_default_format()
                          )));
  
  $entry->created = strtotime($atom_entry->updated);
  
  $entry->old_link = (string)$atom_entry->link['href'];
  
  return $entry;
}

/**
 * Some existing eXtension articles have a teaser/summary embeded.
 * Pull out teaser from HTML to enable us to put in new node.
 *
 * @param string $content HTML content for a 'news' article.
 * @return string HTML for teaser content only
 */
function eximport_get_teaser($content) {
  $summary = "";
  if ( ! empty($content)) {
    $find_sum = '#<div\ id="summary"\ class="printme\ toc">(.*?)</div>#m';
  
    $matches = array();
    $found = preg_match($find_sum, $content, $matches);
  
    if ($found) {
      $summary = $matches[1];
    }
  }
  
  return $summary;
}

/**
 * Find Drupal uid given eXtensionID.
 *
 * @param string $exid eXtension ID string.
 * @return integer Drupal uid if exists, 0 otherwise
 * @see user_load_multiple
 */
function eximport_find_author($exid) {
  $id = 0;
  $account = user_load_by_name($exid);

  if ($account) {
    $id = $account->uid;
  }
  
  return $id;
}

/**
 * Load content from Atom formatted XML file.
 *
 * @param string $filename Input filename with full path.
 * @return array Total number, number added, number errors.
 * @see SimpleXML
 */
function eximport_import_from_file($filename) {
  $added = 0;
  $errors = 0;
  
  $target = eximport_get_fullpath($filename);
  
  $xml = simplexml_load_file($target);
  
  $total = count($xml->entry);
  
  for ($i=0; $i < $total; $i++) {
    $atom_entry = $xml->entry[$i];
    // use an intermediate object to reduce complexity and aid debugging
    $entry = eximport_entry_create($atom_entry);
    $nid = eximport_node_create($entry);
    if ($nid) {
      $added++;
    } else {
      $errors++;
    }
  }
  
  return array($total, $added, $errors);
}

/**
 * Process all revisions of imported nodes.
 *
 * @return array Total number, number added, number errors.
 * @see SimpleXML
 */
function eximport_rewrite_imported_urls() {
  // get imported node list (list of nids)
  $nids = eximport_load_imported_node_list();
  
  $total = 0;
  $processed = 0;
  $errors = 0;
  // loop thru all nodes and get all revisions
  foreach ($nids as $nid) {
    // create fake node to load revision list
    $fakenode = new stdClass();
    $fakenode->nid = $nid;
    $revisions = node_revision_list($fakenode);
    $total += count($revisions);
    foreach ($revisions as $vid => $rev) {
      $node = node_load($nid, $vid);
      $GLOBALS['eximport_nid'] = $node->nid;
      eximport_rewrite_urls($node);
      eximport_node_update_revision($node);
      $processed++;
    }
  }
  return array($total, $processed, $errors);
}

function eximport_load_imported_node_list() {
  return db_query("SELECT source 
             FROM url_alias 
             WHERE source RLIKE '^[[:digit:]]+$'")->fetchCol();
}

/**
 * Update the modified body and summary of a node.
 * WARNING: not using API, direct DB update.
 *
 * @param object $node Reference to a node object
 * @return N/A
 */
function eximport_node_update_revision(&$node) {
  $fields = array(
    'body_value' => $node->body[LANGUAGE_NONE][0]['value'],
    'body_summary' => $node->body[LANGUAGE_NONE][0]['summary']
  );
  
  // update in the revision history
  db_update('field_revision_body')
    ->fields($fields)
    ->condition('revision_id', $node->vid)
    ->execute();
  
  // also update latest version
  db_update('field_data_body')
    ->fields($fields)
    ->condition('revision_id', $node->vid)
    ->execute();
  
  return;
}

/**
 * Rewrite the URLs in the body and summary of a node.
 *
 * @param object $node Reference to a node object
 * @return N/A
 */
function eximport_rewrite_urls(&$node) {
  $html = new simple_html_dom();
  $html->set_callback('eximport_process_element');
  
  // first, the body html
  // using outertext() instead of save() to trigger callback
  $html->load($node->body[LANGUAGE_NONE][0]['value']);
  $node->body[LANGUAGE_NONE][0]['value'] = $html->root->outertext();
  
  // then the summary/teaser html
  $html->load($node->body[LANGUAGE_NONE][0]['summary']);
  $node->body[LANGUAGE_NONE][0]['summary'] = $html->root->outertext();
  
  unset($html);
  return;
}

/**
 * Rewrite the URLs in an anchor element.
 *
 * @param object $element Reference to an DOM element object
 * @return N/A
 */
function eximport_process_element($element) {
  if (! in_array($element->tag, array('a', 'img'))) {
   return;
  }
  
  $orig_url = '';
  
  if ($element->tag == 'a') {
    // only anchors, and not the nautical kind
    
    // not the label kind neither
    if ( empty($element->href) ) {
      return;
    }
    
    $orig_url &= $element->href;
  }
  
  if ($element->tag == 'img') {
    // don't forget those images
    $orig_url &= $element->src;
  }
  
  $url = parse_url($orig_url);
  
  // parseable URL?  note, didn't say valid
  if ($url === FALSE) {
    // bogus, zap the element, leaving the innards
    $element->outertext = $element->innertext;
    return;
  }
  
  eximport_process_url($url);
  
  if ( empty($url) ) {
    // need to zap it
    $element->outertext = $element->innertext;
  } else {
    $orig_url = $url;
  }
  
  return;
}

/**
 * Rewrite the URLs.
 *
 * @param array $url Reference to an array for an URL via parse_url
 * @return N/A
 */
function eximport_process_url(&$url) {
  // get the old URL for the current node
  $current_node_path = path_load($GLOBALS['eximport_nid']);
  $current_node_url = $current_node_path['alias'];
  
  // tells us where we are running
  $my_url = parse_url(http_build_url());
  
  if (! empty($url['scheme'])) {
    // only interested in http
    if ($url['scheme'] != 'http') {
      return;
    }
  } else {
    $new_url = array();
    // handle the relative URLs by fully specifying them
    // using the scheme/host/port from the old URL for this node
    http_build_url($current_node_url, $url, HTTP_URL_REPLACE, $new_url);
    $url = $new_url;
  }
  
  // at this point we have full URLs, let's see what to do with them
  
  $path = $url['path'];
  
  $matches = array();
  $modified = FALSE;
  if (preg_match('#^/wiki/Category\:(.+)#', $path, $matches)) {
    $tag = $matches[1];
    // map to taxonomy/tag URL - need term id
    $term = taxonomy_get_term_by_name($tag);
    if ($term) {
      $path = '/taxonomy/term/' . $term[0]->tid;
      $modified = TRUE;
    } else {
      // not found, zap link
      $url = NULL;
      return;
    }
  } elseif (preg_match('#^/mediawiki/(.*)#', $path, $matches)) {
    // replace 'mediawiki/files' w/ 'sites/default/files/w'
    $path = '/sites/default/files/w/' . $matches[1];
    $modified = TRUE;
  } elseif (preg_match('#^/learninglessons/(.*)#', $path, $matches)) {
    // our work is done, just need to update host below
    $modified = TRUE;
  } elseif (preg_match('#^/wiki/File\:.*#', $path)) {
    // zap it
    $url = NULL;
    return;
  } elseif (preg_match('#^/wiki/Image\:.*#', $path)) {
    // zap it
    $url = NULL;
    return;
  } else {
    // see if it is something we imported, zap the fragment
    $uri = http_build_url($url, array('fragment' => ''));
    $new_path = path_load(array('alias' => $uri));
    if ($new_path) {
      $nid = $new_path['source'];
      $path = '/node/' . $nid;
      $modified = TRUE;
    }
  }
  
  $url['path'] = $path;
  
  if ($modified) {
    $url['host'] = $my_url['host'];
    if (isset($my_url['port'])) {
      $url['port'] = $my_url['port'];
    }
  }
  
  return;
}
